objects/Migration_Job__c.object
<CustomObject>
    <fields>
        <fullName>Base_Object_Migration_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Base Object Migration Rule</label>
        <referenceTo>Migration_Rule__c</referenceTo>
        <relationshipLabel>Migration Jobs</relationshipLabel>
        <relationshipName>Migration_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>List_View_Id__c</fullName>
        <label>List View Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Email_Address__c</fullName>
        <label>Notification Email Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Org Credential</label>
        <referenceTo>Settings__c</referenceTo>
        <relationshipLabel>Migration Jobs</relationshipLabel>
        <relationshipName>Migration_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Send_Notification_Email_On_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Notification Email On Complete</label>
        <type>Checkbox</type>
    </fields>
    <label>Migration Job</label>
    <nameField>
        <label>Migration Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Migration Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Migration_Job_Rule_Hierarchy__c.object
<CustomObject>
    <fields>
        <fullName>Migration_Job__c</fullName>
        <label>Migration Job</label>
        <referenceTo>Migration_Job__c</referenceTo>
        <relationshipLabel>Migration Job Rule Hierarchies</relationshipLabel>
        <relationshipName>Migration_Job_Rule_Hierarchies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Migration_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Migration Rule</label>
        <referenceTo>Migration_Rule__c</referenceTo>
        <relationshipLabel>Migration Job Rule Hierarchies</relationshipLabel>
        <relationshipName>Migration_Job_Rule_Hierarchies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>DML Sort Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Source_Object__c</fullName>
        <formula>Migration_Rule__r.Source_Object__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Source Object</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Object__c</fullName>
        <formula>Migration_Rule__r.Target_Object__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Target Object</label>
        <type>Text</type>
    </fields>
    <label>Migration Job Rule Hierarchy</label>
    <nameField>
        <displayFormat>MH-{00000}</displayFormat>
        <label>Migration Job Rule Hierarchy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Migration Job Rule Hierarchies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Migration_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Callout_Chunk_Size__c</fullName>
        <label>Callout Chunk Size</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Is_self_related__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is self related</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source_Object__c</fullName>
        <label>Source Object</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Object__c</fullName>
        <label>Target Object</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Record_Type__c</fullName>
        <defaultValue>&apos;Default&apos;</defaultValue>
        <label>Target Record Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Migration Rule</label>
    <nameField>
        <displayFormat>MR-{000000}</displayFormat>
        <label>Migration Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Migration Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Migration_Rule_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Destination_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Destination Org</label>
        <referenceTo>Settings__c</referenceTo>
        <relationshipLabel>Migration Rule Mappings</relationshipLabel>
        <relationshipName>Migration_Rule_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_ID_Field__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is ID Field</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Manuel_Entry_Value__c</fullName>
        <label>Manuel Entry Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Migration_Rule__c</fullName>
        <label>Migration Rule</label>
        <referenceTo>Migration_Rule__c</referenceTo>
        <relationshipLabel>Migration Rule Mappings</relationshipLabel>
        <relationshipName>Migration_Rule_Mappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Migration_Type__c</fullName>
        <label>Migration Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Field From Source</fullName>
                    <default>true</default>
                    <label>Field From Source</label>
                </value>
                <value>
                    <fullName>Manuel Entry</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Field__c</fullName>
        <label>Source Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Object__c</fullName>
        <formula>IF(ISPICKVAL(Migration_Type__c,&apos;Field From Source&apos;),Migration_Rule__r.Source_Object__c,&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Source Object</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Field__c</fullName>
        <label>Target Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Migration Rule Mapping</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Migration Rule Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Migration Rule Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Migration_Rule_Relation__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Detail_Migration_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Detail Migration Rule</label>
        <referenceTo>Migration_Rule__c</referenceTo>
        <relationshipLabel>Migration Rule Relations (Detail Migration Rule)</relationshipLabel>
        <relationshipName>Migration_Rule_Relations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Migration_Rule__c</fullName>
        <label>Master Migration Rule</label>
        <referenceTo>Migration_Rule__c</referenceTo>
        <relationshipLabel>Migration Rule Relations</relationshipLabel>
        <relationshipName>Migration_Rule_Relations1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Source_Relationship_Name__c</fullName>
        <label>Relationship Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Migration Rule Relation</label>
    <nameField>
        <displayFormat>MRR-{00000}</displayFormat>
        <label>Migration Rule Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Migration Rule Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Settings__c.object
<CustomObject>
    <label>Org Credential</label>
    <nameField>
        <label>Org Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FieldMappingController_Test.cls
@isTest
private class FieldMappingController_Test {
	
	@isTest static void test_method_one() {
		TestUtil util = new TestUtil();
		Profile p = util.getSystemAdministratorProfile();
		User u = util.userCreate(p.id, 'mock@test.com.migration', 'mock@test.com', 'tester', 'my', 'Avandel Inc');
		Settings__c setting = util.createSetting();
		insert setting;
		Account acc = util.createAccount();
		insert acc;
		System.debug(loggingLevel.Error, '*** acc: ' + JSON.serialize(acc));
		Contact con = util.createContact(acc.id, 'mock@test.com');
		insert con;
		System.debug(loggingLevel.Error, '*** con: ' + JSON.serialize(con));
		List<Migration_Rule__c> rules = new List<Migration_Rule__c>();
		Migration_Rule__c account = new Migration_Rule__c();
		account.Description__c = 'Test migration rule for account';
		account.Is_self_related__c = true;
		account.Source_Object__c = 'Account';
		account.Target_Object__c = 'Account';
		account.Target_Record_Type__c = null;
		account.Callout_Chunk_Size__c = 10;
		rules.add(account);
		Migration_Rule__c contact = new Migration_Rule__c();
		contact.Description__c = 'Test migration rule for contact';
		contact.Is_self_related__c = true;
		contact.Source_Object__c = 'Contact';
		contact.Target_Object__c = 'Contact';
		contact.Target_Record_Type__c = null;
		contact.Callout_Chunk_Size__c = 10;
		rules.add(contact);
		insert rules;
		
		List<Migration_Rule_Mapping__c> maps = new List<Migration_Rule_Mapping__c>();
		Map<String, Schema.SObjectType> gd = Schema.getGlobalDescribe();
		List<TargetFieldWrapper> wrapperList = new List<TargetFieldWrapper>();
		Map<String,SoapType> testTargetFields = new Map<String,SoapType>(); 
		for (Migration_Rule__c mr : rules) {
			Schema.SObjectType ctype = gd.get(mr.Source_Object__c);
			Map<String, Schema.SobjectField> fmap = ctype.getDescribe().fields.getMap();
			for (String f : fmap.keySet()) {
				testTargetFields.put(f,fmap.get(f).getDescribe().getSoapType());
				
				if (f == 'Name') {
					TargetFieldWrapper a = new TargetFieldWrapper(f, fmap.get(f).getDescribe().getSoapType());
					wrapperList.add(a);
					Migration_Rule_Mapping__c mp = new Migration_Rule_Mapping__c(
					    Migration_Rule__c = mr.id,
					    Migration_Type__c = 'Manuel Entry',
					    Manuel_Entry_Value__c = 'Test Map',
					    Target_Field__c = f,
					    Destination_Org__c = setting.id
					);
					maps.add(mp);
				} else {
					TargetFieldWrapper a = new TargetFieldWrapper(f, fmap.get(f).getDescribe().getSoapType(), fmap.get(f).getDescribe().isExternalID());
					wrapperList.add(a);
					Migration_Rule_Mapping__c mp = new Migration_Rule_Mapping__c(
					    Migration_Rule__c = mr.id,
					    Migration_Type__c = 'Field From Source',
					    Source_Field__c = f,
					    Target_Field__c = f,
					    Destination_Org__c = setting.id
					);
					if (fmap.get(f).getDescribe().isExternalID()) {
						mp.Is_ID_Field__c = true;
					}
					if (mp.Is_ID_Field__c == FALSE && f == 'Id') {
						mp.Is_ID_Field__c = TRUE;
					}
					maps.add(mp);
				}
			}
		}
		insert maps;
		Migration_Rule_Relation__c mrr = new Migration_Rule_Relation__c();
		mrr.Master_Migration_Rule__c = account.id;
		mrr.Detail_Migration_Rule__c = contact.id;
		mrr.Description__c = 'Test Account Contact rule relation';
		mrr.Source_Relationship_Name__c = 'Contacts';
		insert mrr;
		String accQuery = 'SELECT Name FROM Account LIMIT 1';
		ApexPages.StandardSetController accSST = new ApexPages.StandardSetController(Database.getQueryLocator(accQuery));
		String listViewId = accSST.getListViewOptions()[0].getValue().left(15);
		Migration_Job__c job = new Migration_Job__c();
		job.Name = 'Test Job';
		job.Org_Credential__c = setting.id;
		job.Base_Object_Migration_Rule__c = account.id;
		job.Send_Notification_Email_On_Complete__c = true;
		job.Notification_Email_Address__c = 'mock@testclass.com';
		job.List_View_Id__c = listViewId;
		insert job;
		List<Migration_Job_Rule_Hierarchy__c> hierarchies = new List<Migration_Job_Rule_Hierarchy__c>();
		Migration_Job_Rule_Hierarchy__c accountH = new Migration_Job_Rule_Hierarchy__c(
		    Migration_Rule__c = account.Id,
		    Migration_Job__c = job.Id,
		    Sort_Order__c = 1
		);
		hierarchies.add(accountH);
		Migration_Job_Rule_Hierarchy__c contactH = new Migration_Job_Rule_Hierarchy__c(
		    Migration_Rule__c = contact.Id,
		    Migration_Job__c = job.Id,
		    Sort_Order__c = 2
		);
		hierarchies.add(contactH);
		insert hierarchies;
		Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(account);
		FieldMappingController cont = new FieldMappingController(sc);
		PageReference pageRef = Page.FieldMapping;
		Test.setCurrentPage(pageRef);
		system.debug('mmmmmm=>'+JSON.serialize(wrapperList));
		Test.setMock(HttpCalloutMock.class, new Test_MockLoginCallout(200, 'OK', JSON.serialize(wrapperList), new Map<String,String>{'ObjectName' => 'Account'}));
		cont.selectedSetting = setting.id;
		cont.retrieveSourceFields();
		cont.retrieveTargetFields();
		cont.targetFields.putAll(testTargetFields);
		cont.targetFieldsState.putAll(testTargetFields);
		cont.sourceFields.putAll(testTargetFields);
		ApexPages.currentPage().getParameters().put('sourceField','Id');
        ApexPages.currentPage().getParameters().put('order','1');
		cont.remove();
		ApexPages.currentPage().getParameters().put('from','Name');
        ApexPages.currentPage().getParameters().put('to','Name');

		cont.autoMapping();
		cont.resetMapping();
		cont.autoMapping();
		cont.SaveState();
		cont.autoMapping();
		cont.remove();
		cont.setMapping();
		cont.setMapping();
		cont.closeModal();
		cont.clearAll();
		cont.autoMapping();
		cont.SaveState();
		ApexPages.currentPage().getParameters().put('sourceField','Id');
        ApexPages.currentPage().getParameters().put('order','1');
		cont.remove();
		ApexPages.currentPage().getParameters().put('manualField','Name');
        ApexPages.currentPage().getParameters().put('manualVal','Test');
        cont.saveManualValue();
        cont.SaveState();
		CheckTypeCompability.check('String','String');

		Test.stopTest();
	}
	@isTest static void test_method_two() {
		TestUtil util = new TestUtil();
		Profile p = util.getSystemAdministratorProfile();
		User u = util.userCreate(p.id, 'mock@test.com.migration', 'mock@test.com', 'tester', 'my', 'Avandel Inc');
		Settings__c setting = util.createSetting();
		insert setting;
		Account acc = util.createAccount();
		insert acc;
		System.debug(loggingLevel.Error, '*** acc: ' + JSON.serialize(acc));
		Contact con = util.createContact(acc.id, 'mock@test.com');
		insert con;
		System.debug(loggingLevel.Error, '*** con: ' + JSON.serialize(con));
		List<Migration_Rule__c> rules = new List<Migration_Rule__c>();
		Migration_Rule__c account = new Migration_Rule__c();
		account.Description__c = 'Test migration rule for account';
		account.Is_self_related__c = true;
		account.Source_Object__c = 'Account';
		account.Target_Object__c = 'Account';
		account.Target_Record_Type__c = null;
		account.Callout_Chunk_Size__c = 10;
		rules.add(account);
		Migration_Rule__c contact = new Migration_Rule__c();
		contact.Description__c = 'Test migration rule for contact';
		contact.Is_self_related__c = true;
		contact.Source_Object__c = 'Contact';
		contact.Target_Object__c = 'Contact';
		contact.Target_Record_Type__c = null;
		contact.Callout_Chunk_Size__c = 10;
		rules.add(contact);
		insert rules;
		List<Migration_Rule_Mapping__c> maps = new List<Migration_Rule_Mapping__c>();
		Map<String, Schema.SObjectType> gd = Schema.getGlobalDescribe();
		List<TargetFieldWrapper> wrapperList = new List<TargetFieldWrapper>();
		for (Migration_Rule__c mr : rules) {
			Schema.SObjectType ctype = gd.get(mr.Source_Object__c);
			Map<String, Schema.SobjectField> fmap = ctype.getDescribe().fields.getMap();
			for (String f : fmap.keySet()) {
				
				if (f == 'Name') {
					TargetFieldWrapper a = new TargetFieldWrapper(f, fmap.get(f).getDescribe().getSoapType());
					wrapperList.add(a);
					Migration_Rule_Mapping__c mp = new Migration_Rule_Mapping__c(
					    Migration_Rule__c = mr.id,
					    Migration_Type__c = 'Manuel Entry',
					    Manuel_Entry_Value__c = 'Test Map',
					    Target_Field__c = f,
					    Destination_Org__c = setting.id
					);
					maps.add(mp);
				} else {
					TargetFieldWrapper a = new TargetFieldWrapper(f, fmap.get(f).getDescribe().getSoapType(), fmap.get(f).getDescribe().isExternalID());
					wrapperList.add(a);
					Migration_Rule_Mapping__c mp = new Migration_Rule_Mapping__c(
					    Migration_Rule__c = mr.id,
					    Migration_Type__c = 'Field From Source',
					    Source_Field__c = f,
					    Target_Field__c = f,
					    Destination_Org__c = setting.id
					);
					if (fmap.get(f).getDescribe().isExternalID()) {
						mp.Is_ID_Field__c = true;
					}
					if (mp.Is_ID_Field__c == FALSE && f == 'Id') {
						mp.Is_ID_Field__c = TRUE;
					}
					maps.add(mp);
				}
			}
		}
		insert maps;
		Migration_Rule_Relation__c mrr = new Migration_Rule_Relation__c();
		mrr.Master_Migration_Rule__c = account.id;
		mrr.Detail_Migration_Rule__c = contact.id;
		mrr.Description__c = 'Test Account Contact rule relation';
		mrr.Source_Relationship_Name__c = 'Contacts';
		insert mrr;
		String accQuery = 'SELECT Name FROM Account LIMIT 1';
		ApexPages.StandardSetController accSST = new ApexPages.StandardSetController(Database.getQueryLocator(accQuery));
		String listViewId = accSST.getListViewOptions()[0].getValue().left(15);
		Migration_Job__c job = new Migration_Job__c();
		job.Name = 'Test Job';
		job.Org_Credential__c = setting.id;
		job.Base_Object_Migration_Rule__c = account.id;
		job.Send_Notification_Email_On_Complete__c = true;
		job.Notification_Email_Address__c = 'mock@testclass.com';
		job.List_View_Id__c = listViewId;
		insert job;
		List<Migration_Job_Rule_Hierarchy__c> hierarchies = new List<Migration_Job_Rule_Hierarchy__c>();
		Migration_Job_Rule_Hierarchy__c accountH = new Migration_Job_Rule_Hierarchy__c(
		    Migration_Rule__c = account.Id,
		    Migration_Job__c = job.Id,
		    Sort_Order__c = 1
		);
		hierarchies.add(accountH);
		Migration_Job_Rule_Hierarchy__c contactH = new Migration_Job_Rule_Hierarchy__c(
		    Migration_Rule__c = contact.Id,
		    Migration_Job__c = job.Id,
		    Sort_Order__c = 2
		);
		hierarchies.add(contactH);
		insert hierarchies;

		Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(account);
		FieldMappingController cont = new FieldMappingController(sc);
		PageReference pageRef = Page.FieldMapping;
		Test.setCurrentPage(pageRef);
		system.debug('mmmmmm=>'+JSON.serialize(wrapperList));
		Test.setMock(HttpCalloutMock.class, new Test_MockLoginCallout(200, 'OK', JSON.serialize(wrapperList), new Map<String,String>{'ObjectName' => 'Account','request' => 'true'}));
		cont.selectedSetting = setting.id;
		cont.retrieveSourceFields();
		cont.retrieveTargetFields();
		cont.retrieveTargetRecordTypes();
		ApexPages.currentPage().getParameters().put('from',job.id);
        ApexPages.currentPage().getParameters().put('to',job.id);
        cont.sourceRecordTypes.put(job.Id , null);
		cont.setRtMapping();
		cont.saveRecordTypeMapping();
		ApexPages.currentPage().getParameters().put('sourceField','Id');
        ApexPages.currentPage().getParameters().put('order','1');
		cont.removeRT();
		cont.setRTWrapperforTest('test', 'test', job.id, 'test', job.id);
		RecordTypeWrapper a = new RecordTypeWrapper(new Map<Id,RecordType>{job.Id => null});
		String mockBody = JSON.serialize(wrapperList);
		RestResponse res = new RestResponse();
		RestRequest req = new RestRequest();
		req.requestURI = '/services/apexrest/MigrateTHIS/transportdata';
		req.addHeader('Content-Type', 'JSON');
		req.addHeader('ObjectName', 'Account');
		req.addHeader('request', 'false');
		req.requestBody = Blob.valueOf(mockBody);
		req.httpMethod = 'GET';
		RestContext.request = req;
		System.assertEquals(req.httpMethod, 'GET');
		RestContext.response = res;
		RestIntegrationHandler.getFields();
		Test.stopTest();
	}
	@isTest static void restService(){

	}
}