objects/Migration_Job__c.object
<CustomObject>
    <fields>
        <fullName>Notification_Email_Address__c</fullName>
        <label>Notification Email Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Org Credential</label>
        <referenceTo>Settings__c</referenceTo>
        <relationshipLabel>Migration Jobs</relationshipLabel>
        <relationshipName>Migration_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Send_Notification_Email_On_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Notification Email On Complete</label>
        <type>Checkbox</type>
    </fields>
    <label>Migration Job</label>
    <nameField>
        <label>Migration Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Migration Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Migration_Log__c.object
<CustomObject>
    <fields>
        <fullName>Data_Result__c</fullName>
        <label>Data Results</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Migration_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Migration Job</label>
        <referenceTo>Migration_Job__c</referenceTo>
        <relationshipLabel>Migration Logs</relationshipLabel>
        <relationshipName>Migration_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ObjectName__c</fullName>
        <label>ObjectName</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Org Credential</label>
        <referenceTo>Settings__c</referenceTo>
        <relationshipLabel>Migration Logs</relationshipLabel>
        <relationshipName>Migration_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>errorMessage__c</fullName>
        <label>errorMessage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>status</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Migration Log</label>
    <nameField>
        <displayFormat>ML-{00000}</displayFormat>
        <label>Migration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Migration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Migration_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Source_Object__c</fullName>
        <label>Source Object</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Migration Rule</label>
    <nameField>
        <displayFormat>MR-{000000}</displayFormat>
        <label>Migration Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Migration Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Migration_Rule_Relation__c.object
<CustomObject>
    <fields>
        <fullName>Target_Relationship_Field__c</fullName>
        <label>Relationship Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Migration Rule Relation</label>
    <nameField>
        <displayFormat>MRR-{00000}</displayFormat>
        <label>Migration Rule Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Migration Rule Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Settings__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Connected_App_Client_Id__c</fullName>
        <label>Connected App Client Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Connected_App_Client_Secret__c</fullName>
        <label>Connected App Client Secret</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Destination_Endpoint__c</fullName>
        <label>Destination Endpoint</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Destination_Org_Password__c</fullName>
        <label>Destination Org Password</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Destination_Org_Security_Token__c</fullName>
        <label>Destination Org Security Token</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Destination_Org_Username__c</fullName>
        <label>Destination Org Username</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchCallout.cls
global class BatchCallout extends AbstractRestfullService implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts  {
	private String QUERYTEMPLATE = 'SELECT {0} FROM {1} WHERE {2} IN: whereIds';
	private String QUERYTEMPLATEMULTI = 'SELECT {0} FROM {1} WHERE {2}';
	private Map<String, Schema.SObjectType> gd = Schema.getGlobalDescribe();
	public Set<String> whereIds {get; set;}
	final Map<Integer, String> orderedMap {get; set;}
	final Map<Id, Migration_Rule__c> migrationRules {get; set;}
	final Map<String, Map<RelationEnum, Map<Id, Migration_Rule_Relation__c>>> MRRelationsMap {get; set;}
	final Map<String, Map<String, String>> literalValues {get; set;}
	private String query {get; set;}
	final Map<Integer, String> dmlPriorityMap {get; set;}
	final Map<String, Map<String, String>> externalMappings {get; set;}
	final Map<String, Boolean> selfRelation {get; set;}
	final Map<String, Map<String, String>> sourceFields {get; set;}
	final Map<String, String> sourceToTarget {get; set;}
	final Migration_Job__c job {get; set;}
	final Integer orderNo {get; set;}
	public String objectName {get; set;}
	private Boolean startIntegration {get; set;}
	public Map<String, Integer> chunckSizeMap {get; set;}
	public Map<String, List<sObject>> objectData {get; set;}
	public Map<String, Map<Id, String>> rtMappings {get; set;}
	private Map<String, List<TransportResultWrapper>> migrationResults = new Map<String, List<TransportResultWrapper>>();
	public BatchCallout(Map<String, List<sObject>> objectData, Boolean startIntegration, Integer orderNo, Migration_Job__c job, String query, Set<String> whereIds, Map<Integer, String> orderedMap, Map<Id, Migration_Rule__c> migrationRules, Map<String, Map<RelationEnum, Map<Id, Migration_Rule_Relation__c>>> MRRelationsMap, Map<String, Map<String, String>> literalValues, Map<Integer, String> dmlPriorityMap, Map<String, Boolean> selfRelation, Map<String, Map<String, String>> externalMappings, Map<String, Map<String, String>> sourceFields, Map<String, String> sourceToTarget, Map<String, Integer> chunckSizeMap, Map<String, Map<Id, String>> rtMappings) {
		this.query = query;
		this.whereIds = whereIds;
		this.orderedMap = orderedMap;
		this.migrationRules = migrationRules;
		this.MRRelationsMap = MRRelationsMap;
		this.literalValues = literalValues;
		this.selfRelation = selfRelation;
		this.externalMappings = externalMappings;
		this.sourceFields = sourceFields;
		this.dmlPriorityMap = dmlPriorityMap;
		this.sourceToTarget = sourceToTarget;
		this.job = job;
		this.orderNo = orderNo;
		this.startIntegration = startIntegration;
		this.objectData = objectData;
		this.chunckSizeMap = chunckSizeMap;
		this.rtMappings = rtMappings;
	}

	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext BC, List<sObject> scope) {
		System.debug(loggingLevel.Error, '*** chunckSizeMap: ' + chunckSizeMap);
		if (!startIntegration) {
			objectName = migrationRules.get(orderedMap.get(orderNo)).Source_Object__c;
			if (objectData.containsKey(objectName)) {
				List<sObject> temp = objectData.get(objectName);
				temp.addAll(scope);
				objectData.put(objectName, temp);
			} else {
				List<sObject> temp = new List<sObject>();
				temp.addAll(scope);
				objectData.put(objectName, temp);
			}
			List<sObject> updatedFields = objectData.get(objectName);
			if (literalValues.containsKey(objectName)) {
				Schema.SObjectType ctype = gd.get(objectName);
				Map<String, Schema.SobjectField> fmap = ctype.getDescribe().fields.getMap();
				Map<String, String> literals = literalValues.get(objectName);
				for (sObject obj : updatedFields) {
					for (String lit : literals.keySet()) {
						Schema.DescribeFieldResult fr = fmap.get(lit).getDescribe();
						if (fr.isAccessible()) {
							ConvertTypes ct = new ConvertTypes(fmap.get(lit));
							ct.putTo(obj, literals.get(lit));
						}
					}
					updatedFields.add(obj);
				}
			}
			objectData.put(objectName, updatedFields);
		} else {
			String jsonString = JSONOperations.generateExternalJSON(objectData, dmlPriorityMap, selfRelation, externalMappings, sourceFields, sourceToTarget, orderNo,rtMappings);
			System.debug(loggingLevel.Error, '*** jsonString: ' + jsonString);
			List<Settings__c> settings = new List<Settings__c>([SELECT Id, Destination_Org_Username__c, Destination_Org_Security_Token__c, Destination_Org_Password__c, Name, Connected_App_Client_Id__c, Connected_App_Client_Secret__c, Destination_Endpoint__c FROM Settings__c WHERE Active__c = true AND Id = : job.Org_Credential__c LIMIT 1]);
			if (!settings.isEmpty()) {
				List<Migration_Log__c> mlList = new List<Migration_Log__c>();
				Settings__c setting = settings[0];
				ClientResource client = new ClientResource(setting.Destination_Org_Username__c, setting.Destination_Org_Password__c, setting.Destination_Org_Security_Token__c);
				String oAuthToken = login(setting, client);
				System.debug(loggingLevel.Error, '*** oAuthToken: ' + oAuthToken);
				if (Test.isRunningTest()) {
					oAuthToken = '5Aep862eWO5D.7wJBuW5aaARbbxQ8hssCnY1dw3qi59o1du7ob.lp23ba_3jMRnbFNT5R8X2GUKN';
				}
				if (!String.isBlank(oAuthToken)) {
					String endPoint = EncodingUtil.urlEncode(setting.Destination_Endpoint__c, 'UTF-8');
					String conObject = IntegrationRequest(oAuthToken, jsonString, endPoint);
					System.debug(loggingLevel.Error, '*** conObject: ' + conObject);
					Migration_Log__c mlRequest = new Migration_Log__c(
					    Type__c = 'Request to ' + endPoint,
					    Org_Credential__c = setting.id,
					    Migration_Job__c = job.id,
					    Status__c = 'Completed'
					);
					if (conObject == null) {
						throw new connectionException('Destination org access token is not found or not valid!!');
						Migration_Log__c mlException = new Migration_Log__c(
						    Type__c = 'Connection Exception',
						    Org_Credential__c = setting.id,
						    Migration_Job__c = job.id,
						    Status__c = 'Failed'
						);
						mlList.add(mlException);
					} else {
						if (conObject != null) {
							try {
								TransportResults tr = (TransportResults)JSON.deserialize(conObject, TransportResults.class);
								if (Test.isRunningTest() && tr.JSONWrapper == NULL) {
									TransportResultWrapper tw = new TransportResultWrapper('Account', '001245436457', 'Completed', '', TRUE);
									tr.JSONWrapper = new Map<String, List<TransportResultWrapper>> {'Account' => new List<TransportResultWrapper>{tw}};
								}
								if (tr.JSONWrapper != null) {
									migrationResults.putAll(tr.JSONWrapper);
								}
							} catch (Exception e) {
							}
						}
					}
				}
			}
		}
	}

	global void finish(Database.BatchableContext BC) {
		if (startIntegration && orderNo == orderedMap.keySet().size()) {
			if (job.Send_Notification_Email_On_Complete__c) {
				Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
				mail.setToAddresses(new String[] {job.Notification_Email_Address__c});
				mail.setSenderDisplayName('MigrateTHIS Job Status');
				mail.setSubject('Job: ' + job.Name + ' completed ');
				mail.setPlainTextBody('Your requested migration job is completed. Please check it\'s logs.');
				Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
			}
		} else if (!startIntegration && orderNo == orderedMap.keySet().size()) {
			startIntegration = true;
			System.schedule('Migration Callouts - Step: 1 - ObjectName: ' + dmlPriorityMap.get(1), Datetime.now().addSeconds(3).format('s m H d M ? yyyy'), new ScheduleCallout(objectData, startIntegration, 1, job, query, whereIds, orderedMap, migrationRules, MRRelationsMap, literalValues, dmlPriorityMap, selfRelation, externalMappings, sourceFields, sourceToTarget,chunckSizeMap,rtMappings) );
		} else if (startIntegration && orderNo != orderedMap.keySet().size()) {
			startIntegration = true;
			try {
				List<Migration_Log__c> mlList = new List<Migration_Log__c>();
				Map<String, Integer> errorMessages = new Map<String, Integer>();
				Integer success = 0;
				for (String mrk : migrationResults.keySet()) {
					for (TransportResultWrapper mr : migrationResults.get(mrk)) {
						if (mr.errorMessage != null && mrk != 'Success') {
							if (errorMessages.containsKey(mr.errorMessage)) {
								Integer i = errorMessages.get(mr.errorMessage);
								errorMessages.put(mr.errorMessage, i++);
							} else {
								errorMessages.put(mr.errorMessage, 1);
							}
						} else if (mrk == 'Success') {
							success++;
						}
					}
				}
				if (success > 0) {
					Migration_Log__c mlResults = new Migration_Log__c(
					    Type__c = 'Result',
					    ObjectName__c = dmlPriorityMap.get(orderNo),
					    Status__c = 'Completed',
					    Org_Credential__c = job.Org_Credential__c,
					    Migration_Job__c = job.id
					);
					if (objectData.containsKey(dmlPriorityMap.get(orderNo))) {
						mlResults.Data_Result__c = success + ' / ' + objectData.get(dmlPriorityMap.get(orderNo)).size();
					}
					mlList.add(mlResults);
				}
				if (!errorMessages.isEmpty()) {
					for (String em : errorMessages.keySet()) {
						Migration_Log__c mlResults = new Migration_Log__c(
						    Type__c = 'Failure',
						    ObjectName__c = dmlPriorityMap.get(orderNo),
						    Status__c = 'Completed',
						    ErrorMessage__c	= em,
						    Org_Credential__c = job.Org_Credential__c,
						    Migration_Job__c = job.id,
						    Data_Result__c = String.valueOf(errorMessages.get(em))
						);
						mlList.add(mlResults);
					}
				}
				if (!mlList.isEmpty()) {
					database.insert(mlList, false);
				}
			} catch (Exception ex) {
			}
			System.schedule('Migration Callouts - Step: ' + (orderNo + 1) + ' - ObjectName: ' + dmlPriorityMap.get(orderNo + 1), Datetime.now().addSeconds(3).format('s m H d M ? yyyy'), new ScheduleCallout(objectData, startIntegration, orderNo + 1, job, query, whereIds, orderedMap, migrationRules, MRRelationsMap, literalValues, dmlPriorityMap, selfRelation, externalMappings, sourceFields, sourceToTarget,chunckSizeMap,rtMappings) );
		} else {
			Integer nextOperation = orderNo + 1;
			if (nextOperation > 1) {
				Set<String> relationField = new Set<String>();
				String nextId = orderedMap.get(nextOperation);
				Map<RelationEnum, Map<Id, Migration_Rule_Relation__c>> operationalRelation = MRRelationsMap.get(nextId);
				for (RelationEnum opId : operationalRelation.keySet() ) {
					for (Id vId : operationalRelation.get(opId).keySet()) {
						String tempRefFeild = operationalRelation.get(opId).get(vId).Target_Relationship_Field__c;
						relationField.add(tempRefFeild);
						relationField.add('Id');
					}
					for (String obj : objectData.keySet()) {
						for (sObject so : objectData.get(obj)) {
							for (String f : relationField) {
								try {
									whereIds.add(String.valueOf(so.get(f)));
								} catch (Exception ex) {}
							}
						}
					}
				}
				query = QueryBuilder(migrationRules.get(orderedMap.get(nextOperation)).Source_Object__c, whereIds, relationField);
			}
			System.schedule('Migration Data Preparation - Step: ' + nextOperation + ' - ObjectName: ' + migrationRules.get(orderedMap.get(nextOperation)).Source_Object__c, Datetime.now().addSeconds(3).format('s m H d M ? yyyy'), new ScheduleCallout(objectData, false, nextOperation, job, query, whereIds, orderedMap, migrationRules, MRRelationsMap, literalValues, dmlPriorityMap, selfRelation, externalMappings, sourceFields, sourceToTarget,chunckSizeMap,rtMappings) );
		}
	}
	private String QueryBuilder(String objectName, Set<String> whereIds) {
		return QueryBuilder(objectName, whereIds, 'Id');
	}
	private String QueryBuilder(String objectName, Set<String> whereIds, String referanceField) {
		List<String> fields = new List<String>();
		fields.addAll(sourceFields.get(objectName).keySet());
		String mergedFields = String.join(fields, ' ,');
		return String.format(QUERYTEMPLATE, new String[] {mergedFields, objectName, referanceField});
	}
	private String QueryBuilder(String objectName, Set<String> whereIds, Set<String> referanceFields) {
		List<String> fields = new List<String>();
		List<String> whereFields = new List<String>();
		fields.addAll(sourceFields.get(objectName).keySet());
		Schema.SObjectType ctype = gd.get(objectName);
		Map<String, Schema.SobjectField> fmap = ctype.getDescribe().fields.getMap();
		for (String f : referanceFields) {
			if (fmap.containsKey(f) && fmap.get(f).getDescribe().isFilterable()) {
				whereFields.add(f);
			}
		}
		String whereClause = String.join(whereFields, ' IN: whereIds OR ') + ' IN: whereIds ';
		String mergedFields = String.join(fields, ' ,');
		return String.format(QUERYTEMPLATEMULTI, new String[] {mergedFields, objectName, whereClause});
	}
}